In [1]:
from sklearn.feature_extraction.text import CountVectorizer
import numpy as np

# 문서 정의
docs = [
    "먹고 싶은 사과",
    "먹고 싶은 바나나",
    "길고 노란 바나나 바나나",
    "저는 과일이 좋아요"
]

# CountVectorizer로 단어 카운트 행렬 생성
vectorizer = CountVectorizer()
X = vectorizer.fit_transform(docs)
print(X)

# numpy 배열로 변환
doc_term_matrix = X.toarray()

# 단어 목록 확인
vocab = vectorizer.get_feature_names_out()

# 결과 출력
print("단어 목록:", vocab)
print("\n문서-단어 행렬:\n", doc_term_matrix)

<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 12 stored elements and shape (4, 9)>
  Coords	Values
  (0, 3)	1
  (0, 6)	1
  (0, 5)	1
  (1, 3)	1
  (1, 6)	1
  (1, 4)	1
  (2, 4)	2
  (2, 1)	1
  (2, 2)	1
  (3, 7)	1
  (3, 0)	1
  (3, 8)	1
단어 목록: ['과일이' '길고' '노란' '먹고' '바나나' '사과' '싶은' '저는' '좋아요']

문서-단어 행렬:
 [[0 0 0 1 0 1 1 0 0]
 [0 0 0 1 1 0 1 0 0]
 [0 1 1 0 2 0 0 0 0]
 [1 0 0 0 0 0 0 1 1]]


In [2]:
from numpy import dot                             # 문서 목록
from numpy.linalg import norm                     # docs = [
                                                  #   "먹고 싶은 사과",
def cosine_similarity(A, B):                      #   "먹고 싶은 바나나",
  return dot(A, B)/(norm(A)*norm(B))              #   "길고 노란 바나나 바나나",
                                                  #   "저는 과일이 좋아요"
for i in range(len(doc_term_matrix)):             # ]
  for j in range(i+1, len(doc_term_matrix)):
    print(f'문서{i+1}과 문서{j+1}의 유사도:')
    print(cosine_similarity(doc_term_matrix[i], doc_term_matrix[j]))
    print('-'*30)

문서1과 문서2의 유사도:
0.6666666666666667
------------------------------
문서1과 문서3의 유사도:
0.0
------------------------------
문서1과 문서4의 유사도:
0.0
------------------------------
문서2과 문서3의 유사도:
0.47140452079103173
------------------------------
문서2과 문서4의 유사도:
0.0
------------------------------
문서3과 문서4의 유사도:
0.0
------------------------------
